### ISSUE TITLE
Allow customizing the volume above "1"

### ISSUE THREAD

**Issue by intercepted16** [M1ndo/Neptune#6]
I feel as if the volume is too low at the default of 1, and the program only allows for going below that. Please add support for a louder volume.

**Comment by M1ndo** [comment]
The volume at 1 is supposedly at max (original volume of keysound), however I'll add it to the to-do list to further increase the volume beyond 1 (100) 

Thanks!

**Comment by intercepted16** [comment]
@M1ndo I tested inputting the volume above 1 and it seems to function perfectly fine. Might just want to roll with it and mention that in the documentation. (maybe add validation so that you can't input it **too** loud?)

**Comment by M1ndo** [comment]
> @M1ndo I tested inputting the volume above 1 and it seems to function perfectly fine. Might just want to roll with it and mention that in the documentation. (maybe add validation so that you can't input it **too** loud?)

Sure thing, thanks for testing. I've been pretty busy, i'll sure to add this stuff this weekend.

**Comment by M1ndo** [comment]
Fixed in the latest update
