### ISSUE TITLE
Audio plays after i lift instead of when i press.

### ISSUE THREAD

**Issue by Redoxahmii** [M1ndo/Neptune#7]
The audio seems to be playing on lifting the finger instead of pressing it which makes it sound weirdly behind when typing.

I type decently fast so it sounds like it's lagging behind a lot.

The lag is due to the sound being played after as far as i can tell.

One other thing i would recommend is to keep the same parsing methods for audios and configs as mechvibes as that would make it directly compatible you'd just need the `.wav` file and the `json` config file they provide.

They currently have an EG Oreo sound which i prefer but i can't be willing to spend time to just make this work on this by creating custom sounds in altogether new patterns.

**Comment by Redoxahmii** [comment]
This issue i have noticed on the `typewriter` and the base `nk-creams` that is on by default.

**Comment by M1ndo** [comment]
Hello @Redoxahmii  this is not an issue with neptune but rather some keysounds don't have sound events for when pressing the key only releasing it the sounds plays.

Some keysounds have up/down event, and some don't. so those are just the default. if its annoying to you then i suggest you either use some other keysound or create a custom sound then set those to when the key gets clicked not released.

**Comment by Redoxahmii** [comment]
Thank you for the quick reply.
From the sounds it seems you're using the same audio packs as mechvibes as far as i can tell.
The `nk-creams` on mechvibes seems to work fine in that regard as it just plays the sound when clicked.
I would love there to be a config for `eg-oreo` they provide by default but i guess i'm gonna have to do it myself in the end.

**Comment by Redoxahmii** [comment]
PS: the article linked for the tutorial for showing how to make own custom audios is not working.

**Comment by M1ndo** [comment]
@Redoxahmii okay i'll take a look at this, and test both, and if its better i'll push an update.
I'll also look at `eg-oreo` config.
About the article, sorry about that my website is kinda down at moment, it will be back up tomorrow.
I'll write an update once this has be resolved. Thanks for the issue.

**Comment by Redoxahmii** [comment]
No prob. I've been looking to get away from electron part of mechvibes for a while now and recently started tinkering with golang.

I was thinking of making this my first application to write in golang but seems like you beat me to the chase so i will support you instead with help.

Reason why i recommended to follow the same parsing method of mechvibes as that would make all the configs and audios they provide compatible with your own software as well as this was the first thought that came to mind when i started.

**Comment by M1ndo** [comment]
@Redoxahmii here's the tutorial incase you want to create yours.
https://blog.ybenel.xyz/post/neptune_tutorial/

PS: thanks for the info, i'm currently looking into this atm.

**Comment by Redoxahmii** [comment]
Thanks for linking the tutorial.
The files i was intending to use for audios is from mechvibes and they have a single file audio which they then assign different sounds through a json parse.
Do i have to create separate singular files from that audio for each key to make this work for EG-Oreo ?

**Comment by M1ndo** [comment]
No you don't need to create too many files from singular ones.
Well as far as I remember mech vibes only contain like 5 files.
Backspace enter spacebar tab then a key for all other keys.
Depending on your liking and to make this easy for everyone you don't need
to custom a json file.
Just rename the file to the right key, so enter key would have a file
enter.wav space bar would be space.wav ... and for all other keys just call
the file fallback.wav if there's more than a fallback file (fallback1
fallback2 ...) they will be played randomly.

If the key sound has keyevent sounds like when you press a key there's a
sound for it and when you release it there's a sound for that as well then
you'll need to edit that json file and add support events to true.

Like you see in the tutorial, if there's anything troubling let me know.

**Comment by M1ndo** [comment]
Closing this issue, after further investigation and testing. Keysound (nk-cream, typewriter) don't support multi-event keys, when attempting to use multi-event it makes a weird sounds as the same sound plays twice upon hitting and releasing the key.
Only valid keysounds which hold seperate sound keys (up and down) support multi-event.
